import type { Character } from "../types/character";

export const MOCK_CHARACTERS: Character[] = [
  {
    id: 1,
    name: "Rick Sanchez",
    status: "Alive",
    species: "Human",
    origin: { name: "Earth (C-137)", url: "https://rickandmortyapi.com/api/location/1" },
    location: { name: "Citadel of Ricks", url: "https://rickandmortyapi.com/api/location/3" },
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
  },
  {
    id: 2,
    name: "Morty Smith",
    status: "Alive",
    species: "Human",
    origin: { name: "unknown", url: "" },
    location: { name: "Citadel of Ricks", url: "https://rickandmortyapi.com/api/location/3" },
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: 3,
    name: "Summer Smith",
    status: "Alive",
    species: "Human",
    origin: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    location: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: 4,
    name: "Beth Smith",
    status: "Alive",
    species: "Human",
    origin: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    location: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: 5,
    name: "Jerry Smith",
    status: "Alive",
    species: "Human",
    origin: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    location: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
  },
  {
    id: 6,
    name: "Abadango Cluster Princess",
    status: "Alive",
    species: "Alien",
    origin: { name: "Abadango", url: "https://rickandmortyapi.com/api/location/2" },
    location: { name: "Abadango", url: "https://rickandmortyapi.com/api/location/2" },
    image: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
  },
  {
    id: 7,
    name: "Abradolf Lincler",
    status: "unknown",
    species: "Human",
    origin: { name: "Earth (Replacement Dimension)", url: "https://rickandmortyapi.com/api/location/20" },
    location: { name: "Testicle Monster Dimension", url: "https://rickandmortyapi.com/api/location/21" },
    image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
  },
  {
    id: 8,
    name: "Adjudicator Rick",
    status: "Dead",
    species: "Human",
    origin: { name: "unknown", url: "" },
    location: { name: "Citadel of Ricks", url: "https://rickandmortyapi.com/api/location/3" },
    image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
  },
];
